logo add
unclechu/place-cursor-at pull request #3
Opened 2018-07-20 09:21 UTC by psikoz

2018-07-20 11:16 UTC, unclechu requested changes
We also must agree about some license to distribute this artwork. Something from the Creative Commons. I'd say: CC BY SA (see https://en.wikipedia.org/wiki/Creative_Commons_license), please say explicitly if you agree with this decision.

2018-07-20 11:16 UTC, unclechu commented on README.md
> +<p align="left"><img src="logo/logotype_horizontal.png" alt="place-cursor-at" height="100px"></p>
1. I don't get what `<p ...>` here for? Maybe remove it?
2. I believe setting `height` as `Npx` is invalid HTML, you supposed to remove `px` suffix.

2018-07-20 11:16 UTC, unclechu commented on logo/icon.svg
> +	 width="153.144px" height="215.509px" viewBox="0 0 153.144 215.509" enable-background="new 0 0 153.144 215.509"
It would be better to get rid of floating point in document size.

2018-07-20 11:16 UTC, unclechu commented on logo/logotype_horizontal.svg
> +	 width="912.237px" height="174.961px" viewBox="0 0 912.237 174.961" enable-background="new 0 0 912.237 174.961"
It would be better to get rid of floating point in document size.

2018-07-20 11:16 UTC, unclechu commented on logo/logotype_vertical.svg
> +	 width="424.741px" height="232.74px" viewBox="0 0 424.741 232.74" enable-background="new 0 0 424.741 232.74"
It would be better to get rid of floating point in document size.

2018-07-20 11:49 UTC, psikoz commented
This logo is licensed under a Creative Commons Attribution 4.0 International License. (https://creativecommons.org/licenses/by/4.0/)

@unclechu , I don't understand very well from github. so I don't want to ruin your repository :/

I have uploaded all the files to the googledrive. Could you please make these changes?

https://drive.google.com/open?id=1wJrVknT4qS27T4eLTyBvimwM6Goal3LM

2018-07-20 15:03 UTC, unclechu commented
@psikoz NP, I'll make these changes by myself. Anyway, you wouldn't mess anything because this PR made on your side, your fork (copy of this repo). Any new commit to your fork to proper branch will be added to this PR.

2018-07-23 10:54 UTC, psikoz commented
Okay, thank you for it.

2021-03-18 22:55 UTC, unclechu commented
@psikoz I pulled your branch and did some minor adjustments. Now the change is merged. I’m closing this pull request as accepted and merged. Thanks for you contribution!

2021-03-18 22:55 UTC, closed without merging